### ISSUE TITLE
Implement service comunication

### ISSUE THREAD

**Issue by codermarcos** [Developers-SP/my-team-web#3]
Create services to REST, and implement tests

## Tasks includes in this feature:

- [x] Create player service
- [x] Create player tests
- [x] Add methods and communication
