### ISSUE TITLE
Add translation

### ISSUE THREAD

**Issue by codermarcos** [Developers-SP/my-team-web#5]
Add languages pt, en, es with i18n

## Tasks includes in this feature:

- [x] Add i18n on project
- [x] Create language pt
- [x] Create language en
- [x] Create language es
- [x] Change language in run time
